export const PROJECTS_ACTION_TYPES = {
  FETCH_PROJECTS_START: 'projects/FETCH_PROJECTS_START',
  FETCH_PROJECTS_SUCCESS: 'projects/FETCH_PROJECTS_SUCCESS',
  FETCH_PROJECTS_FAILED: 'projects/FETCH_PROJECTS_FAILED',
  POST_PROJECT_START: 'projects/POST_PROJECT_START',
  POST_PROJECT_FAILED: 'projects/POST_PROJECT_FAILED',
  POST_PROJECT_SUCCESS: 'projects/POST_PROJECT_SUCCESS',
};